export const CONSTANT = {
  TOTAL_PAGE_DEFAULT: 1,

  QUERY_PARAM_LIMIT: 'limit',
  QUERY_PARAM_OFFSET: 'offset',
  QUERY_PARAM_SEARCH: 'query',
  QUERY_PARAM_MONTH: 'month',
  QUERY_PARAM_EXCEL: 'excel',
  QUERY_PARAM_PAGE: 'page',

  SUGGEST_LIMIT: 10,
  SUGGEST_OFFSET: 0,

  FORMAT_DATE: 'yyyy-MM-dd',

  LIMIT: 20,
  OFFSET: 0,
  CURRENT_LANGUAGE: 'en',
  PAGE_DEFAULT: 1,

  DELAY_TIME_INPUT: 500,
  DELAY_TIME_INPUT_SLOW: 1500,
};
